### ISSUE TITLE
bug: a difference to Java version

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/nexmark-rs#2]
This implementation:

https://github.com/risingwavelabs/nexmark-rs/blob/f07f4622a464a0a7b234b62a01ff9a9306db411a/src/event.rs#L179-L193

Note the `id` used in `Person::last_id(id, cfg)` (L190) and `Person::next_id(id, rng, cfg)` (L192) is the one defined in L182, instead of the one passed in as an argument.

While in the Java version, it is named as `event_id` which is the one passed in as an argument.

https://github.com/nexmark/nexmark/blob/d0556873bb4f115dae82ab34fedc1b2cfd4ebd71/nexmark-flink/src/main/java/com/github/nexmark/flink/generator/model/AuctionGenerator.java#L44-L56

Is it a bug or intended? (If yes, I am working on a fix)

**Comment by wangrunji0408** [comment]
It seems like a bug introduced by https://github.com/risingwavelabs/risingwave/commit/7ed9ea2d2653b5ed939845240a09b7c4befa9da7#diff-5318bbda349f15d4ab95f0a22c3dd1e1b9b0d6c27e50118c171c2e17cdf7f2deR134. cc @KeXiangWang

**Comment by KeXiangWang** [comment]
Sorry🫣, should be a bug.
